# Generated by Django 3.1 on 2020-08-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='city',
            field=models.CharField(choices=[('bj', '北京'), ('sh', '上海'), ('sz', '深圳'), ('gz', '广州'), ('hz', '杭州'), ('xa', '西安')], max_length=2, verbose_name='城市'),
        ),
    ]
